# Generated by Django 4.2.7 on 2024-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datostablaregresion",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("numero_de_corrida", models.IntegerField(null=True)),
                ("idcliente", models.IntegerField(null=True)),
                ("fecha", models.DateField(max_length=255, null=True)),
                ("dia", models.IntegerField(null=True)),
                ("mes", models.IntegerField(null=True)),
                ("anio", models.IntegerField(null=True)),
                ("hora", models.IntegerField(null=True)),
                ("minuto", models.IntegerField(null=True)),
                ("energia_activa", models.FloatField(null=True)),
                ("energia_reactiva", models.FloatField(null=True)),
                ("forecast_energia_activa", models.FloatField(null=True)),
                ("forecast_energia_reactiva", models.FloatField(null=True)),
                (
                    "sectoreconomico",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Infoclientes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(max_length=255, null=True)),
                ("active_energy", models.FloatField(null=True)),
                ("reactive_energy", models.FloatField(null=True)),
                ("voltaje_fa", models.FloatField(null=True)),
                ("voltaje_fc", models.FloatField(null=True)),
                ("idcliente", models.IntegerField(null=True)),
                (
                    "sectoreconomico",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
