# Generated by Django 4.2.7 on 2024-05-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datostablaregresion",
            name="fechahora",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="datostablaregresion",
            name="usuario",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="infoclientes",
            name="fechahora",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="infoclientes",
            name="usuario",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
