# Generated by Django 4.2.7 on 2024-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_manager", "0003_infoclientes_anomalia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datostablaregresion",
            old_name="forecast_energia_activa",
            new_name="anomalia",
        ),
        migrations.RenameField(
            model_name="datostablaregresion",
            old_name="numero_de_corrida",
            new_name="prediccion_consumo_energia",
        ),
        migrations.RemoveField(
            model_name="datostablaregresion",
            name="fechahora",
        ),
        migrations.RemoveField(
            model_name="datostablaregresion",
            name="forecast_energia_reactiva",
        ),
        migrations.RemoveField(
            model_name="datostablaregresion",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="infoclientes",
            name="anomalia",
        ),
        migrations.AlterField(
            model_name="datostablaregresion",
            name="sectoreconomico",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
